version: '3'
services:
  db:
    image: mysql:8.0.16
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
    restart: always
    environment:
      TZ: Asia/Tokyo
      MYSQL_DATABASE: itspkadai
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    command: mysqld
  
volumes:
  mysql_data:
    driver: "local"
