version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
      - image: circleci/mysql:8.0.16
        environment:
          MYSQL_DATABASE: itspkadai
          MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    working_directory: /go/src/github.com/akky2501/itsp-kadai
    steps:
      - checkout
      - run:
          name: Wait for db
          command: dockerize -wait tcp://localhost:3306 -timeout 1m -wait-retry-interval 5s
      - run:
          name: go get
          command: go get -v -t -d ./...
      - run:
          name: go test
          command: go test -v ./...